//_______________________________________________________________________________//
//This app script is the same as the after insert with slight modifications     //
//When a user is deleted from multi-select it removes the user specific field. //
//____________________________________________________________________________//

//Test if current user is added
if(currentValues["Link to User Table"]["User Name"] == "Lucas_Test") {
    //If current user equals "User name" then delete specialty field.
    currentValues["Link to Site Visit"]["Join_Lucas_Test"] = null;

// Dustin Fite    
} else if(currentValues["Link to User Table"]["User Name"] == "Dustin Fite") {
    currentValues["Link to Site Visit"]["Join_Dustin_Fite"] = null;

// Luke Hanson    
} else if(currentValues["Link to User Table"]["User Name"] == "Luke Hanson") {
    currentValues["Link to Site Visit"]["Join_Luke_Hanson"] = null;

// Stephen Clubb
} else if(currentValues["Link to User Table"]["User Name"] == "Stephen Clubb") {
    currentValues["Link to Site Visit"]["Join_Stephen_Clubb"] = null;

// Derek Tyler    
} else if(currentValues["Link to User Table"]["User Name"] == "Derek Tyler") {
    currentValues["Link to Communication Notes"]["Join_Derek_Tyler"] = null;

// Sergey Shamshur    
} else if(currentValues["Link to User Table"]["User Name"] == "Sergey Shamshur") {
    currentValues["Link to Communication Notes"]["Join_Sergey_Shamshur"] = null;

// Christopher Baggett    
} else if(currentValues["Link to User Table"]["User Name"] == "Christopher Baggett") {
    currentValues["Link to Communication Notes"]["Join_Christopher_Baggett"] = null;

// Josh McVickers    
} else if(currentValues["Link to User Table"]["User Name"] == "Josh McVickers") {
    currentValues["Link to Communication Notes"]["Join_Josh_McVickers"] = null;

// James Caul    
} else if(currentValues["Link to User Table"]["User Name"] == "James Caul") {
    currentValues["Link to Communication Notes"]["Join_James_Caul"] = null;

// Andrew Moody    
} else if(currentValues["Link to User Table"]["User Name"] == "Andrew Moody") {
    currentValues["Link to Communication Notes"]["Join_Andrew_Moody"] = null;

// Andy Tucker   
} else if(currentValues["Link to User Table"]["User Name"] == "Andy Tucker") {
    currentValues["Link to Communication Notes"]["Join_Andy_Tucker"] = null;

// Leonard McConniel    
} else if(currentValues["Link to User Table"]["User Name"] == "Leonard McConniel") {
    currentValues["Link to Communication Notes"]["Join_Leonard_McConniel"] = null;

// Mike Tyler    
} else if(currentValues["Link to User Table"]["User Name"] == "Mike Tyler") {
    currentValues["Link to Communication Notes"]["Join_Mike_Tyler"] = null;

// Dylan Tyler    
} else if(currentValues["Link to User Table"]["User Name"] == "Dylan Tyler") {
    currentValues["Link to Communication Notes"]["Join_Dylan_Tyler"] = null;

// Josh Smith   
} else if(currentValues["Link to User Table"]["User Name"] == "Josh Smith") {
    currentValues["Link to Communication Notes"]["Join_Josh_Smith"] = null;

// Thomas Heavey    
} else if(currentValues["Link to User Table"]["User Name"] == "Thomas Heavey") {
    currentValues["Link to Communication Notes"]["Join_Thomas_Heavey"] = null;
    
// Sam Gray
} else if(currentValues["Link to User Table"]["User Name"] == "Sam Gray") {
    currentValues["Link to Communication Notes"]["Join_Sam_Gray"] = null;
    
// Zach Phifer
} else if(currentValues["Link to User Table"]["User Name"] == "Zach Phifer") {
    currentValues["Link to Communication Notes"]["Join_Zach_Phifer"] = null;
    
// Kevan Starr 
} else if(currentValues["Link to User Table"]["User Name"] == "Kevan Starr") {
    currentValues["Link to Communication Notes"]["Join_Kevan_Starr"] = null;

// Chad Lingafelt
} else if(currentValues["Link to User Table"]["User Name"] == "Chad Lingafelt") {
    currentValues["Link to Communication Notes"]["Join_Chad_Lingafelt"] = null;

// Chris Lowery
} else if(currentValues["Link to User Table"]["User Name"] == "Chris Lowery") {
    currentValues["Link to Communication Notes"]["Join_Chris_Lowery"] = null;

// Jessica Bennet
} else if(currentValues["Link to User Table"]["User Name"] == "Jessica Bennet") {
    currentValues["Link to Communication Notes"]["Join_Jessica_Bennet"] = null;

// Allyson Tyler
} else if(currentValues["Link to User Table"]["User Name"] == "Allyson Tyler") {
    currentValues["Link to Communication Notes"]["Join_Allyson_Tyler"] = null;

// McDouglas Perez
} else if(currentValues["Link to User Table"]["User Name"] == "McDouglas Perez") {
    currentValues["Link to Communication Notes"]["Join_McDouglas_Perez"] = null;

// Jennifer Lowery
} else if(currentValues["Link to User Table"]["User Name"] == "Jennifer Lowery") {
    currentValues["Link to Communication Notes"]["Join_Jennifer_Lowery"] = null;

// Levi Gray
} else if(currentValues["Link to User Table"]["User Name"] == "Levi Gray") {
    currentValues["Link to Communication Notes"]["Join_Levi_Gray"] = null;

// Nathan Hammer
} else if(currentValues["Link to User Table"]["User Name"] == "Nathan Hammer") {
    currentValues["Link to Communication Notes"]["Join_Nathan_Hammer"] = null;

// Michael Childress
} else if(currentValues["Link to User Table"]["User Name"] == "Michael Childress") {
    currentValues["Link to Communication Notes"]["Join_Michael_Childress"] = null;

// William Gleaves
} else if(currentValues["Link to User Table"]["User Name"] == "William Gleaves") {
    currentValues["Link to Communication Notes"]["Join_William_Gleaves"] = null;

// Jordan Boatwright
} else if(currentValues["Link to User Table"]["User Name"] == "Jordan Boatwright") {
    currentValues["Link to Communication Notes"]["Join_Jordan_Boatwright"] = null;
    
// Eric Spear
} else if(currentValues["Link to User Table"]["User Name"] == "Eric Spear") {
    currentValues["Link to Communication Notes"]["Join_Eric_Spear"] = null;
    
// Scotty Hinson
} else if(currentValues["Link to User Table"]["User Name"] == "Scotty Hinson") {
    currentValues["Link to Communication Notes"]["Join_Scotty_Hinson"] = null;
    
}










