//_______________________________________________________________________________//
//This app script is the same as the after insert with slight modifications     //
//When a user is deleted from multi-select it removes the user specific field. //
//____________________________________________________________________________//

//currentValues["User Drop Down"] = null;

//Test if current user is added
if(currentValues["Link to User Table"]["User Name"] == "Lucas_Test") {
    //If current user equals "User name" then delete specialty field.
    currentValues["Link to Site Visit"]["Join_Lucas_Test"] = null;

// Dustin Fite    
} else if(currentValues["Link to User Table"]["User Name"] == "Dustin Fite") {
    currentValues["Link to Site Visit"]["Join_Dustin_Fite"] = null;

// Luke Hanson    
} else if(currentValues["Link to User Table"]["User Name"] == "Luke Hanson") {
    currentValues["Link to Site Visit"]["Join_Luke_Hanson"] = null;

// Stephen Clubb
} else if(currentValues["Link to User Table"]["User Name"] == "Stephen Clubb") {
    currentValues["Link to Site Visit"]["Join_Stephen_Clubb"] = null;

// Derek Tyler    
} else if(currentValues["Link to User Table"]["User Name"] == "Derek Tyler") {
    currentValues["Link to Site Visit"]["Join_Derek_Tyler"] = null;

// Sergey Shamshur    
} else if(currentValues["Link to User Table"]["User Name"] == "Sergey Shamshur") {
    currentValues["Link to Site Visit"]["Join_Sergey_Shamshur"] = null;

// Christopher Baggett    
} else if(currentValues["Link to User Table"]["User Name"] == "Christopher Baggett") {
    currentValues["Link to Site Visit"]["Join_Christopher_Baggett"] = null;

// Josh McVickers    
} else if(currentValues["Link to User Table"]["User Name"] == "Josh McVickers") {
    currentValues["Link to Site Visit"]["Join_Josh_McVickers"] = null;

// James Caul    
} else if(currentValues["Link to User Table"]["User Name"] == "James Caul") {
    currentValues["Link to Site Visit"]["Join_James_Caul"] = null;

// Andrew Moody    
} else if(currentValues["Link to User Table"]["User Name"] == "Andrew Moody") {
    currentValues["Link to Site Visit"]["Join_Andrew_Moody"] = null;

// Andy Tucker   
} else if(currentValues["Link to User Table"]["User Name"] == "Andy Tucker") {
    currentValues["Link to Site Visit"]["Join_Andy_Tucker"] = null;

// Leonard McConniel    
} else if(currentValues["Link to User Table"]["User Name"] == "Leonard McConniel") {
    currentValues["Link to Site Visit"]["Join_Leonard_McConniel"] = null;

// Mike Tyler    
} else if(currentValues["Link to User Table"]["User Name"] == "Mike Tyler") {
    currentValues["Link to Site Visit"]["Join_Mike_Tyler"] = null;

// Dylan Tyler    
} else if(currentValues["Link to User Table"]["User Name"] == "Dylan Tyler") {
    currentValues["Link to Site Visit"]["Join_Dylan_Tyler"] = null;

// Josh Smith   
} else if(currentValues["Link to User Table"]["User Name"] == "Josh Smith") {
    currentValues["Link to Site Visit"]["Join_Josh_Smith"] = null;

// Thomas Heavey    
} else if(currentValues["Link to User Table"]["User Name"] == "Thomas Heavey") {
    currentValues["Link to Site Visit"]["Join_Thomas_Heavey"] = null;
    
// Sam Gray
} else if(currentValues["Link to User Table"]["User Name"] == "Sam Gray") {
    currentValues["Link to Site Visit"]["Join_Sam_Gray"] = null;
    
// Zach Phifer
} else if(currentValues["Link to User Table"]["User Name"] == "Zach Phifer") {
    currentValues["Link to Site Visit"]["Join_Zach_Phifer"] = null;
    
// Kevan Starr 
} else if(currentValues["Link to User Table"]["User Name"] == "Kevan Starr") {
    currentValues["Link to Site Visit"]["Join_Kevan_Starr"] = null;

// Michael Childress    
} else if(currentValues["Link to User Table"]["User Name"] == "Michael Childress") {
    currentValues["Link to Site Visit"]["Join_Michael_Childress"] = null;
    
// William Gleaves   
} else if(currentValues["Link to User Table"]["User Name"] == "William Gleaves") {
    currentValues["Link to Site Visit"]["Join_William_Gleaves"] = null;
}











